// Generated by https://quicktype.io

export interface NewHelpRequest {
    id:         number; // id help request
    address:    string;
    lat:        number;
    lng:        number;
    user_id:    number;
    zone_id:    number;
    subzone_id?: number;
}
